### ISSUE TITLE
java.lang.IllegalArgumentException: Registry has no elements!

### ISSUE THREAD

**Issue by sasuked** [unldenis/Hologram-Lib#1]
I Have tried the `ExampleHolograms` class from the readme, and it shows a error.

Version: 1.8.8

```
[HologramLib] Task #6 for HologramLib v1.0.0 generated an exception
java.lang.IllegalArgumentException: Registry has no elements!
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:248) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:966) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.getChatComponentSerializer(WrappedDataWatcher.java:1057) ~[?:?]
        at com.github.unldenis.hologram.line.TextLine.update(TextLine.java:64) ~[?:?]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_312]
        at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404) ~[?:1.8.0_312]
        at com.github.unldenis.hologram.Hologram.setLine(Hologram.java:87) ~[?:?]
        at com.github.unldenis.hologram.ExampleHolograms$1.run(ExampleHolograms.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]       
  ```

**Comment by unldenis** [comment]
Are you using the latest version of protocol lib?

**Comment by sasuked** [comment]
Yes, the lastest provided from spigotmc site.

**Comment by unldenis** [comment]
Ok so maybe something has changed in the packet format.
I'll update you as soon as I have an answer

**Comment by unldenis** [comment]
Solved, I invite you to take a look here. #2
