### ISSUE TITLE
IllegalArgumentException when joining world with some hologram near to me

### ISSUE THREAD

**Issue by AerWyn81** [unldenis/Hologram-Lib#16]
Hi,

Having this exception when I join the world with an hologram near to me

> [15:57:50 WARN]: [HeadBlocks] Plugin HeadBlocks v2.0.7 generated an exception while executing task 31
java.lang.IllegalArgumentException: No serializer found for class java.lang.Byte
	at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:939) ~[ProtocolLib (2).jar:?]
	at com.github.unldenis.hologram.packet.IPackets$PacketsV1_9V1_18.metadataPacket(IPackets.java:205) ~[HeadBlocks-2.0.7.jar:?]
	at com.github.unldenis.hologram.TextLine.show(TextLine.java:42) ~[HeadBlocks-2.0.7.jar:?]
	at com.github.unldenis.hologram.Hologram.show(Hologram.java:131) ~[HeadBlocks-2.0.7.jar:?]
	at com.github.unldenis.hologram.HologramPool.lambda$hologramTick$5(HologramPool.java:150) ~[HeadBlocks-2.0.7.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-17]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-17]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

What should I do to correct the problem? Thank you!
Best regards,

**Comment by unldenis** [comment]
What version does the mc server run?

**Comment by AerWyn81** [comment]
Hi, running on latest PaperMC version : git-Paper-137 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

**Comment by unldenis** [comment]
Use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by AerWyn81** [comment]
I tried, I still have the error :(

**Comment by AerWyn81** [comment]
Hi, the exception persist... :(

In game:
![image](https://user-images.githubusercontent.com/22222045/190498941-68eee11b-e61a-440b-b500-269dbf58a07e.png)

And the exception:

> [22:07:01 WARN]: [HeadBlocks] Plugin HeadBlocks v2.1.0 generated an exception while executing task 20
java.lang.IllegalArgumentException: No serializer found for class java.lang.Byte
	at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:939) ~[ProtocolLib (3).jar:?]
	at com.github.unldenis.hologram.packet.IPackets$PacketsV1_9V1_18.metadataPacket(IPackets.java:224) ~[HeadBlocks-2.1.0.jar:?]
	at com.github.unldenis.hologram.TextLine.show(TextLine.java:45) ~[HeadBlocks-2.1.0.jar:?]
	at com.github.unldenis.hologram.Hologram.show(Hologram.java:144) ~[HeadBlocks-2.1.0.jar:?]
	at com.github.unldenis.hologram.HologramPool.lambda$hologramTick$5(HologramPool.java:159) ~[HeadBlocks-2.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-137]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Protocol lib version: #600 latest build
Paper: Paper version git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6) (latest)

Additional information: it happens when I load the chunk or at least when I connect to the server in the chunk where I have a hologram. It doesn't happen to all holograms. 

Here is the code I use to manage the holograms: https://github.com/AerWyn81/HeadBlocks/blob/master/core/src/main/java/fr/aerwyn81/headblocks/services/HologramService.java

**Comment by unldenis** [comment]
We don't have much information, the error occurs when setting the entity metadata mask to [invisible](https://github.com/unldenis/Hologram-Lib/blob/master/src/main/java/com/github/unldenis/hologram/packet/IPackets.java#L224).
Try to figure out where it comes from from your code that I don't understand from the log.

**Comment by jorgetoh** [comment]
> Hi, the exception persist... :(
> 
> In game: ![image](https://user-images.githubusercontent.com/22222045/190498941-68eee11b-e61a-440b-b500-269dbf58a07e.png)
> 
> And the exception:
> 
> > [22:07:01 WARN]: [HeadBlocks] Plugin HeadBlocks v2.1.0 generated an exception while executing task 20
> > java.lang.IllegalArgumentException: No serializer found for class java.lang.Byte
> > at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:939) ~[ProtocolLib (3).jar:?]
> > at com.github.unldenis.hologram.packet.IPackets$PacketsV1_9V1_18.metadataPacket(IPackets.java:224) ~[HeadBlocks-2.1.0.jar:?]
> > at com.github.unldenis.hologram.TextLine.show(TextLine.java:45) ~[HeadBlocks-2.1.0.jar:?]
> > at com.github.unldenis.hologram.Hologram.show(Hologram.java:144) ~[HeadBlocks-2.1.0.jar:?]
> > at com.github.unldenis.hologram.HologramPool.lambda$hologramTick$5(HologramPool.java:159) ~[HeadBlocks-2.1.0.jar:?]
> > at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-137]
> > at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-137]
> > at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
> > at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 
> Protocol lib version: #600 latest build Paper: Paper version git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6) (latest)
> 
> Additional information: it happens when I load the chunk or at least when I connect to the server in the chunk where I have a hologram. It doesn't happen to all holograms.
> 
> Here is the code I use to manage the holograms: https://github.com/AerWyn81/HeadBlocks/blob/master/core/src/main/java/fr/aerwyn81/headblocks/services/HologramService.java

I have this exact same issue on paper 1.19.2
