### ISSUE TITLE
com.comphenix.protocol.reflect.FieldAccessException

### ISSUE THREAD

**Issue by TUCAOEVER** [unldenis/Hologram-Lib#22]
Using Protocolib 4.8.0 on purple 1.16.5, i got this error.

**Comment by TUCAOEVER** [comment]
```
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.List exists in class PacketPlayOutEntityDestroy.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:369) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:349) ~[?:?]
	at com.github.unldenis.hologram.packet.IPackets$PacketsV1_9V1_18.destroyPacket(IPackets.java:202) ~[?:?]
	at com.github.unldenis.hologram.AbstractLine.<init>(AbstractLine.java:53) ~[?:?]
	at com.github.unldenis.hologram.line.ItemLine.<init>(ItemLine.java:36) ~[?:?]
	at com.github.unldenis.hologram.Hologram.<init>(Hologram.java:87) ~[?:?]
	at com.github.unldenis.hologram.Hologram$Builder.build(Hologram.java:268) ~[?:?]
	at com.promc.chestshopicon.ChestShopICON.display(ChestShopICON.java:63) ~[?:?]
	at com.promc.chestshopicon.Listener.ChunkLoadListener.loadDisplay(ChunkLoadListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor670.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$a$15(PlayerChunk.java:775) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1080) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:536) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.World.getChunkAt(World.java:416) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1306) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-794]
	at net.citizensnpcs.nms.v1_16_R3.util.NMSImpl.addEntityToWorld(NMSImpl.java:319) ~[?:?]
	at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:51) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:271) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:162) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:546) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by unldenis** [comment]
Probably the package is different(look [here](https://wiki.vg/Protocol_version_numbers)). 
As soon as I can take a look.

**Comment by SimonTheSiro** [comment]
Hi, I may have found a solution to the problem.
Minecraft version 1.19 uses a list, while older versions, such as version 1.16, use an integer array.
In the file /java/com/github/unldenis/hologram/packet/IPackets.java in line 203 you get an IntList.
https://github.com/unldenis/Hologram-Lib/blob/348f919f0ec1cf78626b88e3edf49b4d1dc75a70/src/main/java/com/github/unldenis/hologram/packet/IPackets.java#L203
Because 1.16 uses an integer array, an error occurs that no IntList was found.
So to solve the problem, if the version requires it, you can get an Integer array instead of an IntList.
I hope it helps.
